# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160706_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='confirmed_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='confirmed_phone',
            field=models.BooleanField(default=False),
        ),
    ]
