# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20160720_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name_plural': 'users'},
        ),
    ]
