# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20160725_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='purpose',
            field=models.CharField(choices=[('FP', 'Forgot Password'), ('AA', 'Activate Account'), ('CE', 'Confirm Email')], max_length=2),
        ),
    ]
