# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20160726_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_privileged',
            field=models.BooleanField(default=False, help_text='Designates whether this user is privileged'),
        ),
    ]
