# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_myuser_is_privileged'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_intra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_positional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('QUATERLY', 'QUATERLY'), ('HALF-YEARLY', 'HALF-YEARLY'), ('YEARLY', 'YEARLY')], default='MONTHLY', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='multi_bagger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='nifty_future',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='option_calls_covered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='option_calls_uncovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_future',
            field=models.BooleanField(default=False),
        ),
    ]
