# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-18 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180118_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trading_Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_platform', models.CharField(choices=[(b'Quadrigacx_API', b'Quadrigacx_API'), (b'Kraken_API', b'Kraken_API'), (b'Bitfinex_API', b'Bitfinex_API'), (b'Quoine_API', b'Quoine_API')], default=None, max_length=1)),
                ('api_key', models.CharField(max_length=64)),
                ('secret', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
