# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-18 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_trading_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trading_platform',
            name='user',
        ),
        migrations.AddField(
            model_name='trading_platform',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
