# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-18 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180118_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trading_platform',
            name='user',
        ),
        migrations.AddField(
            model_name='trading_platform',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
