# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-18 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20180118_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading_platform',
            name='trading_platform',
            field=models.CharField(choices=[(b'Quadrigacx_API', b'Quadrigacx_API'), (b'Kraken_API', b'Kraken_API'), (b'Bitfinex_API', b'Bitfinex_API'), (b'Quoine_API', b'Quoine_API')], default=None, max_length=100),
        ),
    ]
