# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-25 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20180118_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading_platform',
            name='api_key',
            field=models.CharField(max_length=224),
        ),
        migrations.AlterField(
            model_name='trading_platform',
            name='secret',
            field=models.CharField(max_length=224),
        ),
    ]
