# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_calls_nifty_future'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calls',
            old_name='multi_beggar',
            new_name='achived',
        ),
        migrations.AddField(
            model_name='calls',
            name='multi_bagger',
            field=models.BooleanField(default=False),
        ),
    ]
