# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-25 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_auto_20160725_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='calls',
        ),
    ]
