# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 5, 14, 28, 1, 948908, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
