# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 16:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 7, 5, 16, 32, 50, 713585, tzinfo=utc)),
        ),
    ]
