# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160706_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_message',
            field=models.TextField(default='No Message', max_length=300),
        ),
    ]
