# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160706_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_subject',
            new_name='subject',
        ),
    ]
