# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160706_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default=' ', max_length=300),
        ),
    ]
