# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160707_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
