# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20160707_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
