# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20160708_0024'),
        ('home', '0015_auto_20160707_2247'),
    ]

    operations = [
    ]
