# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20160710_1905'),
        ('home', '0018_auto_20160710_2306'),
    ]

    operations = [
    ]
