# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact us entries'},
        ),
    ]
